Feature/client
Lab-SA/SA pull request #11
Opened 2022-01-29 12:18 UTC by Sub1nJ0

1. MainClient.py 삭제
2. clientgui에 이벤트 연결
3. client setUp, round2 추가
4. basicSA return value로 bu 추가

자세한 내용은 각 commit에 설명을 작성해놓았습니다. 
오류나 수정사항이 있다면 말씀해주시면 감사하겠습니다!

2022-02-02 15:10 UTC, 0JIEUN0 requested changes
혹시 작성하신 내용들에 대해 값들이 원하는 형식으로 나오는지 테스트해보셨나요?

2022-02-02 15:10 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    u = json.loads(s.recv(SIZE, ENCODING))
set-up 에서는 user index 를 받지 않는 걸로 알고 있는데 아닌가요? 서버는 그래서 그렇게 되어있거든요..!

2022-02-02 15:10 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    euv_list, bu = sa.generateSharesOfMask(commonValues["t"], u, my_keys["s_sk"], my_keys["c_sk"], others_keys)
여기 parameter 에 마지막이 빠졌습니다! 확인해주세요.

2022-02-02 15:10 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    yu = sa.generateMaskedInput(u, bu, xu, my_keys["s_sk"], euv_list, s_pk_dic)
여기도 마지막 parameter 에 대한 값을 확인해주세요!

2022-02-03 02:49 UTC, Sub1nJ0 commented on client/BasicSAClient.py
> +    euv_list, bu = sa.generateSharesOfMask(commonValues["t"], u, my_keys["s_sk"], my_keys["c_sk"], others_keys)
앗 넵 아래 내용과 함께 parameter 수정해두겠습니다!

2022-02-03 02:55 UTC, Sub1nJ0 commented on client/BasicSAClient.py
> +    u = json.loads(s.recv(SIZE, ENCODING))
아하 round1 부터 user index가 사용되는데 server 코드에서 user index를 전달해주는 부분을 못찾아서 임시로 set-up 부분에 구현해두었습니다...! 혹시 server 쪽에서는 어느 단계에서 user index를 전달해주는지 알려주실 수 있으신가요??

2022-02-03 03:52 UTC, Sub1nJ0 commented on client/BasicSAClient.py
> +    u = json.loads(s.recv(SIZE, ENCODING))
부분적으로 값이 어떻게 변환되는지 등은 테스트 해보았는데, 아직 전부 다 테스트해보지는 못했습니다...!

2022-02-03 11:26 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    u = json.loads(s.recv(SIZE, ENCODING))
서버는 advertiseKeys 에서 수행합니다! 논문에 그렇게 되어있던걸로 봐서요.

2022-02-04 00:40 UTC, Sub1nJ0 commented
### Client : add Round4(Unmasking), etc... 관련하여

**1. Round4(Unmasking)**
user index와 함께 dropped users의 s_sk, survived users의 bu를 전송합니다.
 - request example = {user index: [{0: s02_sk, 1: s03_sk, ...}, {1: b01, 4: b04, ...}]}

round 1에서 살아남은 user들의 집합인 U2를 구하기 위하여 round1 의 response를 기존의 euv만 존재하는 list형태가 아닌 user index를 포함하는 dic 형태로 가정하고 구현하였습니다. 이에 대한 피드백 주시면 감사하겠습니다!
- round 1. response example (user 0이 받는) = {0: "e00", 1: "e10"}


**2. user index 저장**
round 0 (advertiseKeys) 단계에서 response를 가지고 자신의 user index u를 찾아 저장하는 것으로 구현하였습니다.

**3. BasicSA 함수 사용 parameter 수정완료**
지난번에 빠져있던 마지막 parameter 추가완료하였습니다.

오류나 수정 사항이 있다면 알려주시면 감사하겠습니다!

2022-02-04 00:41 UTC, Sub1nJ0 commented
### Client : add Round4(Unmasking), etc... 관련하여

**1. Round4(Unmasking)**
user index와 함께 dropped users의 s_sk, survived users의 bu를 전송합니다.
 - request example = {user index: [{0: s02_sk, 1: s03_sk, ...}, {1: b01, 4: b04, ...}]}

round 1에서 살아남은 user들의 집합인 U2를 구하기 위하여 round1 의 response를 기존의 euv만 존재하는 list형태가 아닌 user index를 포함하는 dic 형태로 가정하고 구현하였습니다. 이에 대한 피드백 주시면 감사하겠습니다!
- round 1. response example (user 0이 받는) = {0: "e00", 1: "e10"}


**2. user index 저장**
round 0 (advertiseKeys) 단계에서 response를 가지고 자신의 user index u를 찾아 저장하는 것으로 구현하였습니다.

**3. BasicSA 함수 사용 parameter 수정완료**
지난번에 빠져있던 마지막 parameter 추가완료하였습니다.

오류나 수정 사항이 있다면 알려주시면 감사하겠습니다!

2022-02-04 00:59 UTC, 0JIEUN0 approved these changes
LGTM 👍

2022-02-04 00:59 UTC, merged