Create vss.py
Lab-SA/SA pull request #12
Opened 2022-02-02 07:21 UTC by eigenkyeong

BREA의 verifiable secret-sharing입니다.

2022-02-02 15:22 UTC, 0JIEUN0 requested changes
전체적으로 약자로 써둔 것들 (cld, vss 등) 은 주석으로 설명해주시면 좋을 것 같아요.
그리고 n, q, rij, cld, list, t 이런 친구들은 전역으로 있는 것이 아니라 함수 매개변수로 취급해야 하지 않을까요? 이 내용 자체가 다른 모듈에서 사용할 친구들이니까요.

2022-02-02 18:15 UTC, eigenkyeong commented
cld, vss 함수에 대해서는 주석으로 적혀있습니다! vss는 verifiable secret-sharing의 약자입니다.
말씀해주신 것들은 함수 매개변수로 취급되어야 하는 것이 맞고 저는 잘 작동하는지 테스트를 위해 전역으로 써놨던 부분입니다! 매개변수 추가해서 수정했습니다!

2022-02-03 00:51 UTC, 0JIEUN0 commented
적어달라는게 cld, vss 뿐 아니라 다른 t, n, list 이런 것들도 어떤 것을 의미하는지 적어두면 좋을 것 같다는 의미로 얘기한 거였습니다. vss 도 코드 상에서는 명시되어 있지 않아서 말씀드린 거였습니다. 다른 사람이 코드를 보고 적용해야 함을 생각해서 해주시면 감사하겠습니다.

그리고 논문에 명시되어있는  Feldman’s verifiable secret sharing protocol 가 아닌 다른 것으로 구현하셨나요? 어떤 vss 를 구현했는지도 PR 에 명시해주시면 좋겠습니다. 여기서는 commitment 나, verify 하는 것이 안보여서요.

2022-02-04 16:19 UTC, eigenkyeong commented
넵 적어두었습니다!
Feldman’s verifiable secret sharing protocol을 구현한 것이 맞습니다. commitment나 verify 부분은 아직 구현되지 않은 상태입니다.

2022-02-05 02:38 UTC, 0JIEUN0 approved these changes

2022-02-05 02:38 UTC, merged