Feature/new cnn
Lab-SA/SA pull request #15
Opened 2022-02-10 15:35 UTC by eigenkyeong

## 개요
- CNN을 구현한 코드입니다. 

## 작업사항
- 서버와 클라이언트가 호출할 수 있도록 함수로 정의

- setup() : 서버와 클라이언트가 처음 시작할 때 호출합니다. device와 model을 설정해주고 global_model을 리턴해주는 함수입니다. 
- getDataset() : 서버가 호출하는 함수입니다. train_dataset, test_dataset, user_groups를 리턴받고 train_dataset과 user_groups를 클라이언트로 전달해줍니다. 
- get_global_weights(global_model) : 서버가 호출하는 함수입니다. global_model을 인자로 주면 해당 모델의 global_weights를 리턴해줍니다. 
- local_update(global_model, train_dataset, user_groups, idx, epoch) : 클라이언트가 호출하는 함수입니다. 클라이언트의 local_model을 업데이트하고 local_weights를 업데이트해주는 함수로 setup()을 호출하고 리턴받은 global_model, 서버로부터 전송받은 train_dataset과 user_groups, 자신이 몇 번째 클라이언트인지를 의미하는 idx, 몇 번째 학습을 하고 있는지 저장하는 epoch를 인자로 넣어줍니다. 업데이트한 local_model, local_weight 값과 local_loss 값을 리턴해주면 클라이언트는 local_model은 저장하고 서버로 local_weight, local_loss를 전달합니다. 
- update_globalmodel(global_model, local_weight_sum, local_losses) : 서버가 호출하는 함수입니다. 클라이언트로부터 받은 local_weights로 global_model을 업데이트하는 함수입니다. 인자로 global_model과 SA를 통해 얻어진 local_weight_sum, local_losses를 넣어줍니다. 업데이트된 global_model을 리턴해주면 서버는 클라이언트로 global_model을 전송합니다. 
- test_accuracy(local_model, global_model) : 클라이언트가 호출하는 함수입니다. 정확도를 계산해주는 함수이고 인자로 이전에 학습한 결과인 local_model과 서버로부터 전달받은 global_model을 넣어줍니다. 클라이언트는 acc를 리턴받아 서버로 전달해줍니다. 
- add_accuracy(list_acc, epoch) : 서버가 호출하는 함수입니다. 서버는 클라이언트들이 보내준 acc 값들을 배열로 저장했다가 이 함수의 인자로 넣어줍니다. 클라이언트들이 보낸 acc 값들로 학습의 정확도를 저장하고 epoch 매 2회마다 train_loss와 train_accuracy를 출력해줍니다. 
- test_result(global_model, test_dataset) : 서버가 호출하는 함수입니다. global_model과 getDataset()에서 리턴받았던 test_dataset을 인자로 넣어줍니다. 모든 학습이 끝난 후 결과를 출력해주는 함수입니다. 

## 확인할 사항
- Pytorch를 설치해주세요. 

Anaconda 가상 환경에 Pytorch 설치하기 참고 사이트:
https://eunji7267.tistory.com/6
https://theubermensch.tistory.com/60

2022-02-11 04:25 UTC, 0JIEUN0 requested changes

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    if args.model == 'cnn':
음 저희는 args 를 따로 넣어주면서 실행시키는 형태가 아니라 이 부분들은 함수 인자로 넣어줘야 하지 않을까요?
서버나 클라이언트가 이 파일 자체를 실행시키는 게 아니고 `federated_main` 의 함수를 호출하게 되니까요!

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    train_dataset, test_dataset, user_groups = get_dataset(args)
여기 args 도 동일한 의견입니다!

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    return local_model, w, loss
혹시 이거 `local_weight` 를 반환해야 하는 것이 아닌가요?

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    average_weight = average_weights(local_weight_sum)
그때 aggregation 에서 평균값을 보내준다고 합의본 것 같은데 아닌가요?

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    test_acc, test_loss = test_inference(args, global_model, test_dataset)
여기 `args` 도요!

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    local_model = LocalUpdate(args=args, dataset=train_dataset,
여기 `args` 도 같은 의견입니다!

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +    train_accuracy.append(sum(list_acc)/len(list_acc))
python 에서는 전역변수를 사용하려면 `global` 로 명시해줘야 한다고 알고 있는데, 이렇게 해도 문제 없나요?
혹시 이 함수들에 대한 테스트가 완료되었나요?

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +# [인자] : global_model, train_dataset, user_groups, idx(몇 번째 클라이언트인지 인덱스값)
인자 설명에 `epoch` 가 빠졌는데 확인 부탁드려요~!

2022-02-11 04:25 UTC, 0JIEUN0 commented on federated_main.py
> +# 서버는 전달받은 update된 global model과 서버에서 계산한 global_weights를 클라이언트들에게 전송
클라이언트가 `global_weights` 를 가지고 model 을 조작하는 과정이 없는 것 같은데 맞나요?

2022-02-11 05:39 UTC, eigenkyeong commented on federated_main.py
> +    if args.model == 'cnn':
네 그럼 서버와 클라이언트 부분에서 각자 
from options import args_parser
from utils import exp_details
코드를 추가해주고 args를 선언해서 가지고 있으면 될 것 같습니다! 인자로 넣어주는 형태로 수정하겠습니다!

2022-02-11 05:41 UTC, mimwin commented on federated_main.py
> +# 서버는 전달받은 update된 global model과 서버에서 계산한 global_weights를 클라이언트들에게 전송
마지막에 지우는걸로 했는데 그대로 들어갔네요
update 된 global_model만 전송하는걸로 수정하겠습니다.

2022-02-11 05:48 UTC, eigenkyeong commented on federated_main.py
> +    train_dataset, test_dataset, user_groups = get_dataset(args)
수정했습니다!

2022-02-11 05:48 UTC, eigenkyeong commented on federated_main.py
> +    local_model = LocalUpdate(args=args, dataset=train_dataset,
수정했습니다!

2022-02-11 05:51 UTC, eigenkyeong commented on federated_main.py
> +    return local_model, w, loss
맞습니다. 수정했습니다!

2022-02-11 06:01 UTC, mimwin commented on federated_main.py
> +    train_accuracy.append(sum(list_acc)/len(list_acc))
네 테스트는 모두 진행되었습니다 
배열은 global을 선언해주지 않아도 각 함수에서 수정이 가능하다고 합니다 
그래도 모르니 전부 global 키워드를 붙여서 수정하겠습니다

2022-02-11 06:08 UTC, mimwin commented on federated_main.py
> +# 서버는 전달받은 update된 global model과 서버에서 계산한 global_weights를 클라이언트들에게 전송
수정했습니다!

2022-02-11 06:08 UTC, mimwin commented on federated_main.py
> +    train_accuracy.append(sum(list_acc)/len(list_acc))
수정했습니다!

2022-02-11 06:12 UTC, mimwin commented on federated_main.py
> +    test_acc, test_loss = test_inference(args, global_model, test_dataset)
수정했습니다

2022-02-11 06:12 UTC, mimwin commented on federated_main.py
> +    average_weight = average_weights(local_weight_sum)
네 맞습니다 수정했습니다!

2022-02-11 07:21 UTC, 0JIEUN0 commented on federated_main.py
> +    if args.model == 'cnn':
아 제가 생각한 형태는 `setup(gpu, device, model)` 과 같은 모습이었습니다.
지금대로면 외부에서 함수를 사용하는 사람은 setup 의 args 에 정확히 어떤 인자가 포함되어야 하는지 코드를 뜯어보지 않고는 모를 것이고, 현재 저희의 상황에서는 굳이 args 처럼 '가변' 인자를 두는 것이 아니라 필요한 것만 정의해두면 될 거라고 생각해서요 . 어떻게 생각하시나요?

2022-02-12 04:50 UTC, eigenkyeong commented on federated_main.py
> +# [인자] : global_model, train_dataset, user_groups, idx(몇 번째 클라이언트인지 인덱스값)
추가했습니다!

2022-02-12 05:02 UTC, eigenkyeong commented on federated_main.py
> +    if args.model == 'cnn':
args 전역변수로 수정했습니다.

2022-02-13 08:31 UTC, 0JIEUN0 commented
아 그리고 폴더 구조를 지금 봤는데 server, client 처럼 learning 같은 걸로 폴더 하나 만들어서 묶어서 사용하는 건 어떠신가요?
![image](https://user-images.githubusercontent.com/63097207/153745296-12b349b2-83ca-48d8-8064-86adbf23bb31.png)

2022-02-14 10:42 UTC, 0JIEUN0 approved these changes
수고하셨습니다!! 👍✨

2022-02-14 10:42 UTC, merged