Turbo: setup
Lab-SA/SA pull request #22
Opened 2022-03-03 06:23 UTC by 0JIEUN0

## 개요
- Turbo 에 setup 수정

## 작업사항
- Turbo Server 에서 setup 에서 grouping 하는 과정 추가
  - 현재는 각 그룹의 구성원 수가 동일한 것을 가정함 (딱 나누어 떨어진다고 가정)
  - 각 그룹 내에서 사용자의 index 는 0 부터 시작
- setup 에서 서버가 `mask u` 값과 `perGroup` (한 그룹의 구성원 수) 값을 넘겨주는 것 추가

## 확인할 사항

2022-03-03 06:56 UTC, Sub1nJ0 approved these changes
네 모든 수정사항 확인했습니다! 수고 많으셨습니다~!

2022-03-03 09:23 UTC, Sub1nJ0 requested changes
아ㅏ 전체 그룹 수도 추가로 넘겨주게끔 해주실 수 있을까요?? 다른 users는 상관이 없는데, 마지막 L 그룹의 users는 자신이 마지막 그룹에 속하는지를 알아야만 다음 그룹의 j 즉 final stage의 j가 다른 그룹들의 인원수와 동일하지 않고 1명인걸 알고서 계산이 가능할 것 같습니다..!

2022-03-03 09:23 UTC, Sub1nJ0 commented on client/TurboClient.py
> +        # response = {"maskedxij": {}, "encodedxij": {}, "si": {}, "codedsi": {}, "perGroup": 0, "mask_u": 0}
아ㅏ 전체 그룹 수도 추가로 넘겨주게끔 해주실 수 있을까요?? 다른 users는 상관이 없는데, 마지막 L 그룹의 users는 자신이 마지막 그룹에 속하는지를 알아야만 다음 그룹의 j 즉 final stage의 j가 다른 그룹들의 인원수와 동일하지 않고 1명인걸 알고서 계산이 가능할 것 같습니다..!

2022-03-03 09:27 UTC, Sub1nJ0 commented
그리고 TurboServer.py의 final 함수에서 final_barS와 final_tildeS를 가지고 최종적으로 surviving users의 x의 합을 recover해내는 부분도 필요할 것 같습니다..!

2022-03-03 09:50 UTC, 0JIEUN0 commented
아 그건 아직 안 했는데 그럼 이따 추가할게요!

2022-03-03 12:06 UTC, 0JIEUN0 commented
## 추가 사항
- final stage 에는 1명의 user 가 참여하도록 하였으나 기존의 다른 group 의 사용자 수만큼 (`perGroup`) 이 참여하는 것으로 변경
- final tilde S 값으로 sum x 를 계산하는 것 추가. (단, reconstruct 는 아직)

2022-03-03 12:07 UTC, 0JIEUN0 commented on client/TurboClient.py
> +        # response = {"maskedxij": {}, "encodedxij": {}, "si": {}, "codedsi": {}, "perGroup": 0, "mask_u": 0}
논의 후 final stage 에서도 같은 수의 사용자가 참여함을 가정하고 변경했습니다!

2022-03-04 00:12 UTC, Sub1nJ0 approved these changes
수정사항 확인했습니다! 감사합니다~!

2022-03-04 05:54 UTC, merged