Client: Add AdvertiseKeys(Round 0), ShareKeys(Round 1)
Lab-SA/SA pull request #7
Opened 2022-01-15 16:38 UTC by QqwweerrttyyU

MainClient.py : client에 대한 기본적인 요소들을 담은 class MainClient 가 존재합니다.
BasicSAClient.py : client 측에서 AdvertiseKeys(Round 0), ShareKeys(Round 1) 단계를 진행합니다.

**AdvertiseKeys(Round 0)**

- c_pk, s_pk를 json 형태로 server에 전송 (request)

**ShareKeys(Round 1)**

- 모든 users의 c_pk, s_pk를 json 형태로 수신 (response)
- 자신의 euv를 list 형태로 server에 전송 (request)

코드 구조상 수정사항이나 구현 오류(특히 송수신 데이터 관련)가 있다면 피드백 주시면 감사하겠습니다!

2022-01-16 07:50 UTC, mimwin commented
Round0, Round1 논문대로 잘 짜여진 거 같습니다!!

정말 고생 많으셨습니다!

2022-01-17 03:19 UTC, 0JIEUN0 requested changes

2022-01-17 03:19 UTC, 0JIEUN0 commented on client/MainClient.py
> +class MainClient:
이 친구는 클라이언트에서 필요없을것 같은데 아닌가요?
특별한 기능이 없고 여기에 정의해둔 변수들만 사용하고 있는데, 이 경우는 그냥 `BasicSAClient` 에서 정의해두면 되지 않을까 해서요.
(server 의 경우 중복된 기능을 위해 따로 base class 를 둔 것입니다!)

2022-01-17 03:19 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    s.close()
여기서 자기 데이터 보내고 server 로부터 다른 사용자들의 public key 도 받은 다음에 socket close 해야 합니다!
(그냥 socket close 해버리면 서버는 데이터 보낼 수 없습니다. 이 라운드는 다른 데이터를 받는 것까지 포함 아닌가요?)
+) round1 에서도 데이터 받는 것 없이 종료해버리는데 그거랑 같이 봐주세요.

2022-01-17 03:19 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    while (client.endTime - client.startTime) < client.interval:
`recv` 는 blocking 함수고, client 는 server 내용을 '기다리는' 역할이 아니기 때문에 (계속 열어두고 기다리는 것은 서버) 이렇게 시간을 두고 기다릴 필요가 없습니다!
(물론 `recv` 쪽으로 timeout 을 둘 수는 있지만, 지금은 그 때문에 두신 것은 아니신 것 같고, timeout 을 설정해두시지도 않으셔서요 얘는 그냥 receive 가 없으면 계속 기다리게 됩니다)

2022-01-17 03:41 UTC, QqwweerrttyyU commented on client/BasicSAClient.py
> +    s.close()
논문 내 프로토콜 설명상 server가 round n에서 전송하는 데이터를 client는 round n+1에서 수신, 저장한다는 내용을 보았습니다.
ex) server가 round 0에서 전송한 모든 유저의 public key를 client는 round 1에서 수신
그래서 round 1에서 모든 유저의 public key를 수신하는 방식으로 구현하였는데 혹시 아닌가요...?

2022-01-17 03:41 UTC, QqwweerrttyyU commented on client/MainClient.py
> +class MainClient:
넵 수정하겠습니다!

2022-01-17 03:41 UTC, QqwweerrttyyU commented on client/BasicSAClient.py
> +    while (client.endTime - client.startTime) < client.interval:
아하ㅏ 넵 수정하겠습니다!

2022-01-17 03:44 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    s.close()
아아아 알고리즘 설명에선 그럴게 되어있긴하네요
그래도 구현할때는 수신받고 끝내야 되는게
클라이언트가 소켓 끊어버리면 서버는 못 주고 (지금 TCP 로 구현되어있어서 connection 끊어지는 것) 클라 소켓 정보를 클라 요청이 없으면 서버가 찾아낼 수 없어요

2022-01-17 03:52 UTC, QqwweerrttyyU commented on client/BasicSAClient.py
> +    s.close()
아하ㅏㅏ 그럼 다음 round를 바로 실행해서 client가 다시 연결 요청을 보낸다고 해도 한 번 연결이 끊어지면 server가 데이터를 전송할 수 없는 건가요?? 아 round 마다의 client가 서로 다른 객체이기 때문인가요??

2022-01-17 04:00 UTC, 0JIEUN0 commented on client/BasicSAClient.py
> +    s.close()
다시 연결 요청을 보내면 다른 소켓이 되는데 자기가 어떤 데이터를 보냈는지 혹은 어떤 데이터를 받아야하는지 서버에 또 알려줘야 하는데 (서버 입장에서는 또 다른 client가 되죠 다른 인증 프로세스가 없는한) 애초에 그렇게 할 필요 없이 받고 끝내면 되지 않겠냐고 제안을 드린 것입니다.

다른 'client 객체'여서가 아니라 socket 통신 (그 중에서 TCP) 을 하기 때문입니다. socket에 대해 한번 찾아보시기 바랍니다.

2022-01-17 04:03 UTC, QqwweerrttyyU commented on client/BasicSAClient.py
> +    s.close()
아ㅏㅏ 네넵 그럼 round마다 바로 수신하는 것으로 수정하겠습니다!

2022-01-17 05:02 UTC, QqwweerrttyyU commented on client/BasicSAClient.py
> +    s.close()
이것 포함하여 제안주신 모든 수정사항 수정해서 commit했습니다!

2022-01-17 05:49 UTC, 0JIEUN0 approved these changes
server 에게 받아온 값을 처리 (다른 값들 저장 등) 하는 것과 `c_pk` 등을 `BasicSA` 모듈을 사용해서 구현하는 것 부탁드려요!

2022-01-17 05:49 UTC, merged