Feature/server2
Lab-SA/SA pull request #8
Opened 2022-01-16 09:46 UTC by eigenkyeong

## Round2 (MaskedInputCollection)
각 client로부터 y_u를 받아서 모든 다른 client에게 broadcast합니다. 

- requests example: { (0, y1), (1, y2), (3, y3), ... }

## Round4 (Unmasking)
각 client로부터 drop된 client에 대한 su_sk, drop되지 않은 client에 대한 b_uv를 받습니다. 

- # requests example: { [{0: s02_sk, 1: s03_sk, ...}, {1: b01, 4: b04, ...}], ... }

받은 값들을 재구성하여 전체 y_u에서 빼주어 output z를 구합니다. 
값을 재구성하는 부분은 BasicSA와 SecureProtocol을 참고해야할 것 같습니다. 

구조나 구현 부분에 대해서 수정사항이나 오류가 있다면 피드백 주시면 감사하겠습니다!

2022-01-17 03:06 UTC, 0JIEUN0 requested changes

2022-01-17 03:06 UTC, 0JIEUN0 commented on server/BasicSAServer.py
> +        response[i] = requestData[0]
`requests` 에 사용자가 순서대로 들어가있을 수 있지 않아서, `response` 에 `requests` 를 enumverate 해서 나온 `i` 를 넣으면 사용자가 섞일 것 같아요 (저 `i` 를 사용자 index 로 생각해서 하신게 맞다면)

그리고 requestData[0] 은 index 가 아닌가요?

2022-01-17 03:06 UTC, 0JIEUN0 commented on server/BasicSAServer.py
> +    # su_sk = sp.reconstruct(share_list)
PR 내용에서 말씀하셨지만, 여기서 `BasicSA` 를 이용해서 구현하셔야 합니다. (이미 `BasicSA` 는 작성되어있으니..)
그리고 지금 `BasicSA` 의 `unmasking` 과는 좀 다른 형태로 보이는데 이런 경우 작성하신 분과 협의하시거나 수정하시면 됩니다.

2022-01-17 03:18 UTC, eigenkyeong commented on server/BasicSAServer.py
> +    # su_sk = sp.reconstruct(share_list)
네 협의 후 수정하겠습니다.

2022-01-17 04:09 UTC, eigenkyeong commented on server/BasicSAServer.py
> +        response[i] = requestData[0]
requestData[0]이 사용자 index를 의미합니다

그럼 response를 오름차순 정렬하면 될까요??

2022-01-17 04:14 UTC, 0JIEUN0 commented on server/BasicSAServer.py
> +        response[i] = requestData[0]
response 에는 yu 가 들어가야하는거 아닌가요?
즉 `response[responseData[0]] = responseData[1]`
여야하는거 아닌가 해서요!

2022-01-17 04:17 UTC, eigenkyeong commented on server/BasicSAServer.py
> +        response[i] = requestData[0]
아 서버가 client로부터 yu 값들을 받고 yu를 전송한 client의 목록을 전송해줍니다! 
따라서 { (0, y1), (1, y2), (3, y3), ... } 이런 값을 받았다면 response에는 { 0, 1, 3, ... } 이런 값들이 들어가야 합니다

2022-01-17 04:29 UTC, 0JIEUN0 commented on server/BasicSAServer.py
> +        response[i] = requestData[0]
아아 그 서버에서 저장하는 값이랑 헷갈렸네요!
서버에 `yu` 값들을 저장하는 부분이 없는데, 해당 부분이 추가되어야 할 것 같습니다.

2022-01-24 14:43 UTC, 0JIEUN0 requested changes

2022-01-24 14:43 UTC, 0JIEUN0 commented on server/BasicSAServer.py
> +        totalNum = totalNum + 1
억서 totalNum 을 따로 넣어둔 이유는 무엇인가요? server.userNum 이랑 결국엔 똑같아지지 않나요?

2022-01-24 14:43 UTC, 0JIEUN0 commented on server/BasicSAServer.py
> +    for n in range(totalNum):
이게 totalNum 은 drop-out 에 의해 처음보다 크기가 바뀔 수 있는데, 그걸 index 로 써도 되나요?
처음에 서버가 index 를 정해주는데, 그걸 이용해야 하지 않나 해서요!
(ex. 처음엔 5명이었는데 중간에 3명이 됐으면, 여기서의 totalNum 이 3이 되고, 그럼 자기 index 가 4 인 user 가 살아남았다면 그 내용은 다루지 않는 걸로 보여서요.)

2022-01-25 14:32 UTC, eigenkyeong commented on server/BasicSAServer.py
> +    for n in range(totalNum):
서버가 처음에 index를 정해주는 것을 생각 못 했습니다! 수정하겠습니다!!

2022-02-04 15:52 UTC, eigenkyeong commented on server/BasicSAServer.py
> +        response[i] = requestData[0]
추가했습니다!

2022-02-04 15:54 UTC, eigenkyeong commented on server/BasicSAServer.py
> +        totalNum = totalNum + 1
네 totalNum은 처음에 시작하는 user수로 수정했습니다!

2022-02-05 02:36 UTC, 0JIEUN0 approved these changes

2022-02-05 02:38 UTC, merged